[package]
name = "ficus-agent-aws"
version = "0.1.0"
edition = "2021"

[dependencies]
ficus-agent-lib = {path = "../../lib"}
async-trait = "0.1.58"
aws-config = "0.51.0"
aws-sdk-ec2 = "0.21.0"
aws-sdk-cloudwatch = "0.21.0"
